#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;

function includeIfExists($file)
{
    return file_exists($file) && include $file;
}

if (
    !includeIfExists(__DIR__ . '/vendor/autoload.php') &&
    !includeIfExists(__DIR__ . '/../../../../autoload.php') &&
    !includeIfExists(__DIR__ . '/../../vendor/autoload.php') &&
    !includeIfExists(__DIR__ . '/../../../../../../vendor/autoload.php')
) {
    fwrite(STDERR, 'Install dependencies using Composer.'.PHP_EOL);
    exit(1);
}

if (!class_exists(Application::class)) {
    fwrite(STDERR, 'You need the "symfony/console" installed to run list-tests' . PHP_EOL);
    exit(1);
}


$application = new Application();

$application->add(new \Testomatio\Command());
$application->setDefaultCommand('check-tests', true);
$application->run();